/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.report_card_maker_ah;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author 342513926
 */
public class MainEvent extends javax.swing.JFrame {
    String c1, c2, c3, c4, grade, fName, lName, fullName;
    int index=0;
    ArrayList<ArrayList<String>> data = new ArrayList<>();
    
    

    /**
     * Creates new form NewJFrame
     */
    @SuppressWarnings("empty-statement")
    public static void Calculator(int ind){
        ArrayList<ArrayList<JTextField>> boxes = new ArrayList<>();
        JFrame calculator = new JFrame("");
        calculator.setResizable(false);
        JButton add = new JButton("Add");
        JButton calculate = new JButton("Calculate");
        JTextField result = new JTextField("",10);
        result.setFocusable(false);
        result.setEditable(false);
        calculator.add(calculate);
        calculator.add(add);
        calculator.add(result);
        calculator.add(new JLabel(" Grade      ",SwingConstants.LEFT));
        calculator.add(new JLabel("    Weight",SwingConstants.RIGHT));
        calculator.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        int width = 200, height = 300;
        calculator.setSize(width,height);
        FlowLayout flowLayout = new FlowLayout();
        calculator.setLayout(flowLayout);
        calculator.setVisible(true);
        for(int x = 0; x<5; x++){
            boxes.add(new ArrayList<>());
            for(int y = 0;y<2; y++){
                boxes.get(x).add(new JTextField(5));
                calculator.add(boxes.get(x).get(y));
            }
        }
        add.addActionListener((ActionEvent e) -> {
            boxes.add(new ArrayList<>());
            add.setVisible(false);
            result.setVisible(false);
            calculate.setVisible(false);
            for(int i = 0;i<2;i++){
                boxes.get(boxes.size()-1).add(new JTextField(5));
                calculator.add(boxes.get(boxes.size()-1).get(i));
            }
            add.setVisible(true);
            result.setVisible(true);
            calculate.setVisible(true);
            int h = calculator.getHeight();
            calculator.setSize(200,h+=33);
        });
        calculate.addActionListener((ActionEvent a) -> {
            try{
            int size = boxes.size(); 
            double weightTotal=0;
            double finalGrade=0;
            boolean valid = true;
            for (int i=0;i<size;i++){
                String gradeString,weightString;
                double grade;
                double weight;
                if (boxes.get(i).get(0).getText().isEmpty() || 
                        boxes.get(i).get(1).getText().isEmpty()){
                        break;
                }else{
                    gradeString = boxes.get(i).get(0).getText();
                    grade = Double.parseDouble(gradeString);
                    weightString = boxes.get(i).get(1).getText();
                    weight = Double.parseDouble(weightString);
                }
                weightTotal+=weight;
                finalGrade += grade*(weight/100.0);
                if (weightTotal>100){
                    valid = false;
                    break;
                }
                
            }
            if (weightTotal<100){
                finalGrade+= 100*((100-weightTotal)/100);
            }
            finalGrade = (Math.round(finalGrade*10))/10.0;
            if (valid){
                result.setText(Double.toString(finalGrade));
                switch (ind) {
                    case 1 -> c1ScoreField.setText(Double.toString(finalGrade));
                    case 2 -> c2ScoreField.setText(Double.toString(finalGrade));
                    case 3 -> c3ScoreField.setText(Double.toString(finalGrade));
                    case 4 -> c4ScoreField.setText(Double.toString(finalGrade));
                    default -> {
                    }
                }
            }else{
                result.setText("Invalid data");
            }
            }
            catch(NumberFormatException e){
                result.setText("Invalid data");
            }
        });
       
    }
    public MainEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gradeField = new javax.swing.JTextField();
        fNameField = new javax.swing.JTextField();
        lNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        studentNumberField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        c3NameField = new javax.swing.JTextField();
        c3ScoreField = new javax.swing.JTextField();
        c3MedField = new javax.swing.JTextField();
        c3CommentField = new javax.swing.JTextField();
        c3CalcButton = new javax.swing.JButton();
        c4NameField = new javax.swing.JTextField();
        c4ScoreField = new javax.swing.JTextField();
        c4CalcButton = new javax.swing.JButton();
        c4MedField = new javax.swing.JTextField();
        c4CommentField = new javax.swing.JTextField();
        c1NameField = new javax.swing.JTextField();
        c1ScoreField = new javax.swing.JTextField();
        c1MedField = new javax.swing.JTextField();
        c1CommentField = new javax.swing.JTextField();
        c1CalcButton = new javax.swing.JButton();
        c2NameField = new javax.swing.JTextField();
        c2ScoreField = new javax.swing.JTextField();
        c2CalcButton = new javax.swing.JButton();
        c2MedField = new javax.swing.JTextField();
        c2CommentField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        newStudent = new javax.swing.JButton();
        search = new javax.swing.JButton();
        studentDoesNotExist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Report Cards");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Report Card Maker");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Course 1:");

        jLabel5.setText("Course 2:");

        jLabel6.setText("Course 3:");

        jLabel7.setText("Course 4:");

        jLabel8.setText("Course Name");

        jLabel9.setText("Score");

        jLabel10.setText("Grade:");

        jLabel11.setText("Student #:");

        jLabel12.setText("Median");

        jLabel13.setText("Comments");

        jPanel1.setLayout(null);

        c3NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3NameFieldActionPerformed(evt);
            }
        });

        c3MedField.setEditable(false);

        c3CalcButton.setFont(new java.awt.Font("sansserif", 0, 8)); // NOI18N
        c3CalcButton.setText("Calc");
        c3CalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3CalcButtonActionPerformed(evt);
            }
        });

        c4NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4NameFieldActionPerformed(evt);
            }
        });

        c4CalcButton.setFont(new java.awt.Font("sansserif", 0, 8)); // NOI18N
        c4CalcButton.setText("Calc");
        c4CalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4CalcButtonActionPerformed(evt);
            }
        });

        c4MedField.setEditable(false);

        c1NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1NameFieldActionPerformed(evt);
            }
        });

        c1MedField.setEditable(false);

        c1CalcButton.setFont(new java.awt.Font("sansserif", 0, 8)); // NOI18N
        c1CalcButton.setText("Calc");
        c1CalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1CalcButtonActionPerformed(evt);
            }
        });

        c2NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2NameFieldActionPerformed(evt);
            }
        });

        c2CalcButton.setFont(new java.awt.Font("sansserif", 0, 8)); // NOI18N
        c2CalcButton.setText("Calc");
        c2CalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2CalcButtonActionPerformed(evt);
            }
        });

        c2MedField.setEditable(false);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        newStudent.setText("New Student");
        newStudent.setEnabled(false);
        newStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        studentDoesNotExist.setForeground(new java.awt.Color(255, 51, 51));
        studentDoesNotExist.setText("Student does not exist.");
        studentDoesNotExist.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newStudent)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gradeField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(studentNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(lNameField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentDoesNotExist)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel8)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel9)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel12)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(c4NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c4ScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c4MedField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c4CommentField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c4CalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(c2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(c2ScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(c2MedField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(c1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(c1ScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(c1MedField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(c2CommentField, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(c1CommentField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(c1CalcButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(c2CalcButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c3NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c3ScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c3MedField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c3CommentField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c3CalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c1CalcButton, c2CalcButton, c3CalcButton, c4CalcButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(search)
                    .addComponent(studentDoesNotExist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(gradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1ScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1CommentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1CalcButton)
                            .addComponent(c1MedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2ScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2CommentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2CalcButton)
                            .addComponent(c2MedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(c3NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3ScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3CommentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3CalcButton)
                    .addComponent(c3MedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(c4NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4ScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4CommentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4CalcButton)
                    .addComponent(c4MedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(newStudent))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c3NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3NameFieldActionPerformed

    private void c3CalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3CalcButtonActionPerformed
        // TODO add your handling code here:
        Calculator(3);
    }//GEN-LAST:event_c3CalcButtonActionPerformed

    private void c4NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4NameFieldActionPerformed

    private void c4CalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4CalcButtonActionPerformed
        // TODO add your handling code here:
        Calculator(4);
    }//GEN-LAST:event_c4CalcButtonActionPerformed

    private void c1NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1NameFieldActionPerformed

    private void c1CalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1CalcButtonActionPerformed
        // TODO add your handling code here:
        Calculator(1);
    }//GEN-LAST:event_c1CalcButtonActionPerformed

    private void c2NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2NameFieldActionPerformed

    private void c2CalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2CalcButtonActionPerformed
        // TODO add your handling code here:
        Calculator(2);
    }//GEN-LAST:event_c2CalcButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        data.add(new ArrayList<>());
        c1 = c1NameField.getText();
        c2 = c2NameField.getText();
        c3 = c3NameField.getText();
        c4 = c4NameField.getText();
        grade = gradeField.getText();
        fName = fNameField.getText();
        lName = lNameField.getText();
        fullName = fName.strip() + " " + lName.strip();
        data.get(index).add(0, fullName);
        data.get(index).add(1, studentNumberField.getText());
        data.get(index).add(2, c1ScoreField.getText());
        data.get(index).add(3,c1CommentField.getText());
        data.get(index).add(4,c2ScoreField.getText());
        data.get(index).add(5,c2CommentField.getText());
        data.get(index).add(6,c3ScoreField.getText());
        data.get(index).add(7,c3CommentField.getText());
        data.get(index).add(8,c4ScoreField.getText());
        data.get(index).add(9, c4CommentField.getText());
        newStudent.setEnabled(true);
        
        
        
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        fName = fNameField.getText();
        lName = lNameField.getText();
        fullName = fName.strip() + " " + lName.strip();
        while(true){
            int i=0;
            if (data.get(i).get(0).equals(fullName)){
                    index = i;
                    gradeField.setText(grade);
                    c1NameField.setText(c1);
                    c2NameField.setText(c2);
                    c3NameField.setText(c3);
                    c4NameField.setText(c4);
                    c1ScoreField.setText(data.get(i).get(2));
                    c2ScoreField.setText(data.get(i).get(4));
                    c3ScoreField.setText(data.get(i).get(6));
                    c4ScoreField.setText(data.get(i).get(8));
                    c1CommentField.setText(data.get(i).get(3));
                    c2CommentField.setText(data.get(i).get(5));
                    c3CommentField.setText(data.get(i).get(7));
                    c4CommentField.setText(data.get(i).get(9));
                    break;
            }
            i++;
        }
    }//GEN-LAST:event_searchActionPerformed

    private void newStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentActionPerformed
        // TODO add your handling code here:
        index = data.size()+1;
        data.add(new ArrayList<>());
        gradeField.setText(grade);
        c1NameField.setText(c1);
        c2NameField.setText(c2);
        c3NameField.setText(c3);
        c4NameField.setText(c4);
        fNameField.setText("");
        lNameField.setText("");
        studentNumberField.setText("");
        c1ScoreField.setText("");
        c2ScoreField.setText("");
        c3ScoreField.setText("");
        c4ScoreField.setText("");
        c1CommentField.setText("");
        c2CommentField.setText("");
        c3CommentField.setText("");
        c4CommentField.setText("");
        newStudent.setEnabled(false);
    }//GEN-LAST:event_newStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c1CalcButton;
    private javax.swing.JTextField c1CommentField;
    private javax.swing.JTextField c1MedField;
    private javax.swing.JTextField c1NameField;
    public static javax.swing.JTextField c1ScoreField;
    private javax.swing.JButton c2CalcButton;
    private javax.swing.JTextField c2CommentField;
    private javax.swing.JTextField c2MedField;
    private javax.swing.JTextField c2NameField;
    public static javax.swing.JTextField c2ScoreField;
    private javax.swing.JButton c3CalcButton;
    private javax.swing.JTextField c3CommentField;
    private javax.swing.JTextField c3MedField;
    private javax.swing.JTextField c3NameField;
    public static javax.swing.JTextField c3ScoreField;
    private javax.swing.JButton c4CalcButton;
    private javax.swing.JTextField c4CommentField;
    private javax.swing.JTextField c4MedField;
    private javax.swing.JTextField c4NameField;
    public static javax.swing.JTextField c4ScoreField;
    private javax.swing.JTextField fNameField;
    private javax.swing.JTextField gradeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lNameField;
    private javax.swing.JButton newStudent;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton search;
    private javax.swing.JLabel studentDoesNotExist;
    private javax.swing.JTextField studentNumberField;
    // End of variables declaration//GEN-END:variables
}
